#!/bin/bash
set -eu

mkdir -p src && cd src
git clone https://github.com/drone/drone .
rm .dockerignore
cp ../Dockerfile .
tag=$(git describe --tags --abbrev=0)
version=${tag#v}
echo "Building tag: $tag"
git checkout tags/$tag -b $version

docker build -t $IMAGE_NAME .

docker tag $IMAGE_NAME $DOCKER_REPO:${version}
docker tag $IMAGE_NAME $DOCKER_REPO:${version%.*}
docker tag $IMAGE_NAME $DOCKER_REPO:${version%%.*}
docker push $DOCKER_REPO:${version}
docker push $DOCKER_REPO:${version%.*}
docker push $DOCKER_REPO:${version%%.*}
