#!/bin/bash
set -eu

mkdir -p src && cd src
git clone https://github.com/drone/drone .
rm .dockerignore
cp ../Dockerfile .
export TAG=$(git describe --tags --abbrev=0)
echo "Building tag: $TAG"

docker build -t $IMAGE_NAME src

version=${TAG#v}
docker tag $IMAGE_NAME $DOCKER_REPO:${version}
docker tag $IMAGE_NAME $DOCKER_REPO:${version%.*}
docker tag $IMAGE_NAME $DOCKER_REPO:${version%%.*}
docker push $DOCKER_REPO:${version}
docker push $DOCKER_REPO:${version%.*}
docker push $DOCKER_REPO:${version%%.*}