#!/bin/bash

mkdir -p src && cd src
git clone https://github.com/drone/drone .
rm .dockerignore
cp ../Dockerfile .
tag=$(git describe --tags --abbrev=0)
echo "Building tag: $tag"
version=${tag#v}

docker build -t latest -t $DOCKER_REPO:${version} -t $DOCKER_REPO:${version%.*} -t $DOCKER_REPO:${version%%.*} .
